Make sure ORT lib location is known to cmake
astro-informatics/purify pull request #358
Opened 2024-10-08 14:31 UTC by 20DM

To fix @mmcleod89's issue discussed on slack.

2024-10-08 14:58 UTC, 20DM commented
Unclear why some of them failed, but we should probably anyway merge the Sopt PR first to have a consistent ORT setup in Cmake 🤔

2024-10-08 15:16 UTC, mmcleod89 approved these changes

2024-10-09 10:23 UTC, tkoskela requested changes

2024-10-09 10:23 UTC, tkoskela commented on .github/workflows/ci.yml
> +        ln -s $OLDSOPT $NEWSOPT
Could we remove this from this PR in favour of #359?

2024-10-09 10:46 UTC, tkoskela approved these changes

2024-10-09 11:01 UTC, tkoskela commented
How many places can you hard-code your version in :joy: 

```
$ rg '3\.1\.0'
cmake_files/version.cmake
2:set(${PROJECT_NAME}_VERSION 3.1.0)

data/config/test_simulation_config.yaml
2:Version: 3.1.0

data/config/config.yaml
2:Version: 3.1.0

data/config/test_measurements_config.yaml
2:Version: 3.1.0
```

2024-10-09 11:28 UTC, merged